sudo: required
services:
  - docker

before_install:
  - docker build -t timvg80/docker-react -f Dockerfile.dev .

script:
  - docker run timvg80/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-437927076461"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"